import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

cnn_Kenergy_a1_2 = np.load('cnn_Kenergy_a-1_0-7.npy')
cnn_Kenergy_a22_2 = np.load('cnn_Kenergy_a-22_0-7.npy')
cnn_Kenergy_a02_2 = np.load('cnn_Kenergy_a02_0-7.npy')
cnn_Kenergy_a2_3 = np.load('cnn_Kenergy_a-22_3.npy')
cnn_Kenergy_a1_3 = np.load('cnn_Kenergy_a-1_3.npy')
cnn_Kenergy_a0_3 = np.load('cnn_Kenergy_a02_3.npy')

fft_Kenergy_a1_2 = np.load('fft_Kenergy_a-1_0-7.npy')
fft_Kenergy_a22_2 = np.load('fft_Kenergy_a-22_0-7.npy')
fft_Kenergy_a02_2 = np.load('fft_Kenergy_a02_0-7.npy')
fft_Kenergy_a2_3 = np.load('fft_Kenergy_a-22_3.npy')
fft_Kenergy_a1_3 = np.load('fft_Kenergy_a-1_3.npy')
fft_Kenergy_a0_3 = np.load('fft_Kenergy_a02_3.npy')
Kenergy_3 = np.load('3_Kenergy.npy')
Kenergy_2 = np.load('2_Kenergy.npy')
fig = plt.figure(0,figsize=(10,8))
k = np.linspace(0,15,15)
plt.plot(k,cnn_Kenergy_a1_2[0:15],'g--',label='CNN-low')
plt.plot(k,cnn_Kenergy_a22_2[0:15],'r--',label='CNN-high')
plt.plot(k,cnn_Kenergy_a02_2[0:15],'b--',label='CNN-constant')
plt.plot(k,fft_Kenergy_a1_2[0:15],'g-*',label='fft-low')
plt.plot(k,fft_Kenergy_a22_2[0:15],'r-*',label='fft-high')
plt.plot(k,fft_Kenergy_a02_2[0:15],'b-*',label='fft-constant')
plt.plot(k,Kenergy_2[0:15],'y',label='non-train')
plt.legend()
plt.savefig("singular_vector_2.png" )
fig = plt.figure(1,figsize=(10,8))
k = np.linspace(0,15,15)
plt.plot(k,cnn_Kenergy_a1_3[0:15],'g--',label='CNN-low')
plt.plot(k,cnn_Kenergy_a2_3[0:15],'r--',label='CNN-high')
plt.plot(k,cnn_Kenergy_a0_3[0:15],'b--',label='CNN-constant')
plt.plot(k,fft_Kenergy_a1_3[0:15],'g-*',label='fft-low')
plt.plot(k,fft_Kenergy_a2_3[0:15],'r-*',label='fft-high')
plt.plot(k,fft_Kenergy_a0_3[0:15],'b-*',label='fft-constant')
plt.plot(k,Kenergy_3[0:15],'y',label='non-train')
plt.legend()
plt.savefig("singular_vector_3.png" )